### ISSUE TITLE
Duda sobre despliegue

### ISSUE THREAD

**Issue by iblancasa** [dgiim/blog#103]
Buenas.
Quería haceros una preguntilla sobre cómo realizáis el despligue:
* Editáis el post
* Lo subís a _post
* Travis inicia
* Travis ejecuta ``bundle exec jekyll build``

Ahí me pierdo: ¿dónde publicáis el resultado de esa ejecución? es decir, la carpeta "_site". Al estar el blog en http://dgiim.github.io/blog/ entiendo que sería en la rama "gh-pages" de este mismo repo pero... no lo encuentro.

¿Alguien que despeje mis dudas?

Gracias :D

**Comment by fdavidcl** [comment]
Hola @iblancasa,

GitHub Pages usa Jekyll como generador del sitio, así que nosotros no tenemos que hacer nada. Tras cada *push*, GitHub compila el sitio y lo sirve. El directorio _site de hecho está en el [.gitignore](https://github.com/dgiim/blog/blob/gh-pages/.gitignore) para evitar que una generación en local se suba y estropee la build de GitHub.

Travis no tiene mucho que ver, GitHub no espera a conocer el estado de la build para servirla.

**Comment by iblancasa** [comment]
@fdavidcl vale, no sabía lo de que GitHub crea su propia build. Además, pensaba que estabais usando Travis para el despliegue.

¡Muchas gracias!

**Comment by fdavidcl** [comment]
@iblancasa Sin problema. Por si quieres hacer tu propio sitio en Jekyll/GH Pages, te aviso de que en GitHub la funcionalidad es limitada: no puedes usar plugins de Jekyll, nada más que activar los ya incluidos por defecto. Por lo demás, es muy similar.

**Comment by M42** [comment]
Una idea que teníamos en mente era hacer del blog una plantilla forkeable de blog colaborativo. Ahora mismo está lejos de eso, pero lo que hay puede servir de base.
