### ISSUE TITLE
Desplegar en tux.ugr.es

### ISSUE THREAD

**Issue by M42** [dgiim/blog#105]
Relacionado con #96. Teniendo un espacio cedido en tux.ugr.es, podríamos desplegar allí el blog e ir configurando lo necesario para que se sincronice bien con lo que se sube a GitHub.

**Comment by M42** [comment]
Creo que no hemos ido documentando el proceso de esta issue. ¿Qué falta y qué está ya hecho?

**Comment by JJ** [comment]
@fdavidcl tiene ya las credenciales.

**Comment by M42** [comment]
Sí, tenemos credenciales, ¡gracias! Creo que @fdavidcl estuvo probando también la integración de todo en GitHub; así que, a la espera de que me corrija él, falta sólo que el servidor muestre la página.

**Comment by fdavidcl** [comment]
Faltan unos ajustes en Travis para que haga un despliegue correctamente. Una vez esté eso se estará mostrando en el puerto 3000 él solito.

**Comment by fdavidcl** [comment]
Y ya funciona: http://tux.ugr.es:3000/blog/ Se regenera automáticamente desde Travis y se manda a Tux con cada push a gh-pages (así que mucho cuidado con hacer pushes directamente). Lo único feo es que he tenido que restringir la versión de Jekyll a 2.4.0, porque Jekyll 3 nos rompe la paginación.

El QA está corriendo temporalmente en http://tux.ugr.es:3001, por cierto

**Comment by M42** [comment]
Ya están funcionando blog y foro. Falta pasarlos al puerto 80, pero imagino que para eso habría que pasar la configuración de nuestro nginx a la del que está sirviendo por puerto 80.

**Comment by fdavidcl** [comment]
@JJ, ¿sería razonable usar algo así en el *nginx* que está escuchando el puerto 80 en Tux?

~~~
location /dgiim {
  proxy_pass http://127.0.0.1:3000/;
}
~~~

*(donde pongo 3000 puede ser cualquier otro puerto, alguno que se sepa seguro que no se va a utilizar para otra cosa)*

De esa forma podríamos nosotros servir el blog, sea en Jekyll o de forma estática con otro nginx, y el QA y lo que sea; creo que es más cómodo para todos pero no sé si será un problema para el servidor, si será mucha carga en caso de que se use luego para más cosas o algo...

**Comment by JJ** [comment]
¿Tenemos tal cosa? :-)

Sí, no creo que sea problema. Por favor, ponnos un ticket en
software-libre.ugr.es/redmine y trataremos de atanderlo rápido.

**Comment by fdavidcl** [comment]
Hecho! No tenemos prisa ninguna. Muchas gracias ^.^

**Comment by M42** [comment]
Tenemos el blog ya desplegado en [tux.ugr.es/dgiimblog](http://tux.ugr.es/dgiimblog), así que podemos cerrar esta issue.
