### ISSUE TITLE
Crear una cuenta de Twitter para el blog

### ISSUE THREAD

**Issue by M42** [dgiim/blog#11]
Buscar un nombre para la cuenta del blog del doble grado y crearla usando como avatar el logo.

**Comment by makixun** [comment]
Algo así como: INMA Blog? xD

**Comment by makixun** [comment]
@INMAblog

**Comment by M42** [comment]
Por coherencia con el nombre de Github, sería @blogDGIIM, o @dgiim o algo del estilo.

**Comment by JCEntrena** [comment]
Yo me encargo.

**Comment by JCEntrena** [comment]
Hecha: https://twitter.com/dgiimBlog
La cuenta de correo asociada de gmail es dgiim.blog@gmail.com, puede usarse en el futuro. 
Os paso las contraseñas por privado.
