### ISSUE TITLE
Post: ¿Cómo contribuir a un proyecto de software libre?

### ISSUE THREAD

**Issue by M42** [dgiim/blog#120]
Después de ver [la charla de](https://github.com/vterron/sed-hackers) @vterron, a uno le entran ganas de contribuir a un proyecto de software libre. ¿Cómo elegir dónde contribuir?¿Cómo debo trabajar en un proyecto de software libre?

**Comment by JJ** [comment]
1. Conocer git
2. Abrirse una cuenta en GitHub
3. Hacer un fork de algún repositorio que interese, por el tema, porque es una dependencia de uno en el que se está trabajando, por lo que sea.
3. Mirar el fichero CONTRIBUTING.md que tienen muchos repositorios.
4. Mirar los issues abiertos y/o los pull request que hay abiertos. Si hay muchos pull requests abiertos, quizás no los estén aceptando. Los issues, sin embargo, sirven para saber qué cosas le puede interesar al desarrollador.
5. Hacer el pull request y completarlo con lo que requiera el autor del repo. 

Algunos consejos para colaboraciones fáciles:
1. Seguir las instrucciones de instalación del repo y, si algo no funciona, modificar el README.md y hacer un pull request sobre el mismo.
2. Mirar la ortografía o la gramática de comentarios y documentación, modificar y mejorar la misma.
3. Si no tiene integración continua con Travis u otro sistema, añadir .travis.yml.
4. Borrar ficheros que no sirvan.
5. Muy importante: hacer commits "atómicos", no un sólo commit con todas las modificaciones, especialmente si no están relacionadas. Si se cambia la ortografía, uno por párrafo o incluso frase. Un commit por función, un commit por nuevo fichero añadido o borrado. Así es más fácil a quien acepta el pull request aceptarlo haciendo "cherry-picking"

Por último, consejos para encontrar proyectos a los que contribuir. Afortunadamente, en la UGR hay cientos de proyectos iniciados por grupos de investigación o compañeros, del ámbito académico o pachangas propias. No tienes que contribuir tu primera vez, o posiblemente nunca, a LLVM o al kernel de linux; puede ser a la práctica de 2º de carrera de tu compañero o al TFM de alguien de tu pueblo, o quizás a un trabajo de investigación de algún grupo como GeNeura http://github.com/geneura-papers. Si quieres sugerencias, en la lista de Telegram de software libre de la UGR seguro que hay alguien que necesite ayuda.

**Comment by josemam** [comment]
<ol start="6"><li>
Traducir al castellano, si el CONTRIBUTING.md y el contenido del repositorio facilitan la labor y no está hecha.</li>
</ol>

Adicionalmente se podría hablar de cómo animar al resto de usuarios a que contribuyan a tu propio proyecto: cómo presentar un buen README, cómo redactar un buen CONTRIBUTING...

Y cómo se debería colaborar si el proyecto que nos interesa no tiene CONTRIBUTING ni issues abiertos sin asignar.
