### ISSUE TITLE
GPG

### ISSUE THREAD

**Issue by M42** [dgiim/blog#125]
Post de enlaces sobre el uso de claves públicas y privadas con **pgp**.

**Comment by tzae** [comment]
Algunas notas que tenía sobre este tema:

PGP (del inglés, *Pretty Good Privacy*) es un programa que te permite tener tu propia
identidad digital a través de la criptografía pública. Esto te permite firmar documentos digitalmente y encriptar texto con información privada o mensajes, de tal manera que sólo la persona a la que va dirigido el mensaje pueda leerlo.

Existen varios programas que permiten utilizar este [éstandar](https://tools.ietf.org/html/rfc4880). En esta guía utilizaremos [GNU Privacy Guard](https://www.gnupg.org) (GPG).
Es posible que el programa ya esté instalado en tu ordenador, prueba a ejecutarlo utilizando `gpg --version`.

En caso de que no esté instalado puedes descargarlo desde [aquí](https://www.gnupg.org/download) o desde los repositorios de tú distribución (el paquete usualmente se llama `gpg`).
También tienes instrucciones de instalación detalladas para  [Windows](https://ssd.eff.org/en/module/how-use-pgp-windows) y [Mac](https://ssd.eff.org/en/module/how-use-pgp-mac-os-x).

### Cómo funciona

Una identidad en PGP es un par de claves: una de ellas es pública (conocida por todo
el mundo) y la otra es privada (sólo la conoce la persona a la que pertenece esa identidad).

### Creando una identidad

- Seguir la guía de la EFF

### Introducción

- [Phil's PGP Docs](https://www.phildev.net/pgp/gpgtrust.html)
- [Pretty Good Privacy](https://en.m.wikipedia.org/wiki/Pretty_Good_Privacy)
- [Introducción a PGP](https://ssd.eff.org/es/module/una-introducci%C3%B3n-la-criptograf%C3%ADa-de-llave-p%C3%BAblica-y-pgp)
- [Cómo usar PGP](https://ssd.eff.org/en/module/how-use-pgp-linux)

### Qué debería contener

- [privacy - Best practices for GPG user ids - Information Security Stack Exchange](http://security.stackexchange.com/questions/67259/best-practices-for-gpg-user-ids)

### Expiración de una identidad

- Mirar en RiseUp

### Cuántas claves

- [How many OpenPGP keys should I make?](http://security.stackexchange.com/questions/29851)
- [General purpose GnuPG key setup?](http://security.stackexchange.com/questions/31594)

#### Subclaves

- [Subkeys - Debian Wiki](https://wiki.debian.org/Subkeys?action=show&redirect=subkeys)
- [gnupg - How to manage GPG keys across multiple systems? - Super User](http://superuser.com/questions/466396/how-to-manage-gpg-keys-across-multiple-systems)

### Cómo difundir tú clave

- [How should I distribute my public key?](http://security.stackexchange.com/questions/406)

### Firmar claves

- [Making and verifying signatures](https://www.gnupg.org/gph/en/manual/x135.html)

### Mejores prácticas

- [PGP Best Practices](https://help.riseup.net/en/security/message-security/openpgp/best-practices)
- [GnuPG Frequently Asked Questions](https://www.gnupg.org/faq/gnupg-faq.html)
