### ISSUE TITLE
Crear una lista de ideas de post

### ISSUE THREAD

**Issue by M42** [dgiim/blog#127]
Como una página separada, y cerrar a su vez, todas las issues de posts.

**Comment by oxcar103** [comment]
- [ ] Conjetura de Frankl
- [ ] ¿Cómo contribuir a un proyecto de software libre?
- [ ] Introducción a la Topología Algebraica
- [ ] ¿Cómo estudiar matemáticas?
- [ ] Estándar MIDI
- [ ] ¿Cómo funciona el blog?
- [ ] Problemas abiertos en matemáticas
- [ ] Longest Increasing Subsequence
- [ ] Topological Sort
- [ ] Page Rank
- [ ] Futurama theorem
- [ ] Números ordinales
- [ ] Introducción a la geometría proyectiva
- [ ] Análisis de redes eléctricas
- [ ] Gerrymandering
- [ ] Evaluación perezosa
- [ ] Word problem
- [ ] Disjoint-set forests
- [ ] Hadwiger-Nelson problem
- [ ] Fast inverse square root
- [ ] Teorema Incompletitud Gödel
- [ ] Curvas elípticas
- [ ] P-NP
- [ ] Banach-Tarski
