### ISSUE TITLE
Imagen o foto de cabecera

### ISSUE THREAD

**Issue by M42** [dgiim/blog#13]
La cabecera del blog (y del foro) podría contener una foto o una imagen.

**Comment by M42** [comment]
Que además podríamos aprovechar para la cabecera de la cuenta creada en #11.

**Comment by M42** [comment]
Estaría bien sacar fotos en los seminarios.

**Comment by oxcar103** [comment]
Oye, creo que ya podemos hacer esto, no tenemos muchas fotos de seminarios pero hay algunas :laughing:

(Óscar reabriendo issues muertos :eyes: )

**Comment by M42** [comment]
La primera imagen que tenemos en el [dgiim/home](dgiim/home) parece buena para esto.

**Comment by M42** [comment]
Tenemos imágenes en dgiim/home, y usarla aquí ralentizaría mucho.
