### ISSUE TITLE
Arreglar el paginador de Jekyll

### ISSUE THREAD

**Issue by fdavidcl** [dgiim/blog#14]
La última vez que probamos, el paginador fallaba. Comprobar su funcionamiento de nuevo y arreglarlo.

**Comment by JCEntrena** [comment]
Los permalinks rompen la paginación. Evitadlos sobre todas las cosas.

**Comment by m-andres** [comment]
Sugerencia: en #37 hemos quitado el enlace a archivo que había, y ya no hay ningún enlace a una lista de posts ordenados por fecha de publicación. Podríamos aprovechar el paginador y poner también un enlace a lo que era el archivo antes.

**Comment by pbaeyens** [comment]
:tada::tada:
