### ISSUE TITLE
Sincronizar Twitter y RSS

### ISSUE THREAD

**Issue by M42** [dgiim/blog#15]
Para la cuenta creada en #11. Podríamos hacer que escribiera por cada actualización del RSS del blog.

**Comment by fdavidcl** [comment]
Añadida [receta de IFTTT](https://ifttt.com/recipes/268845-if-new-post-on-rss-then-tweet-it-out). 

Podríamos también usar Buffer para añadir otro tweet más tarde (un día o dos días después) como un "ICYMI" (*in case you missed it*).

**Comment by JJ** [comment]
Se puede hacer directamente también desde gitHub, con un post-push hook.
Mirad en WebHooks.

**Comment by m-andres** [comment]
Añadida la [receta de IFTTT](https://ifttt.com/recipes/269085-in-case-you-missed-it-tweet) con Buffer, para que se publique otro tweet el viernes siguiente.

**Comment by fdavidcl** [comment]
@jj Los webhooks se lanzan con cada push, pero habría que controlar que sea un post nuevo y todo el rollo. Parece más sencillo con IFTTT, aunque le echaremos un vistazo de todas formas.

**Comment by JJ** [comment]
Se pueden filtrar, creo. Pero si IFTTT funciona, santa palabra.
