### ISSUE TITLE
Post: LaTeX

### ISSUE THREAD

**Issue by pbaeyens** [dgiim/blog#19]
Escribir un post (y quizás añadir recursos) como introducción básica a LaTeX y con una lista de recursos, documentos y webs útiles para utilizarlo.

**Comment by pbaeyens** [comment]
Mencionar #17.

**Comment by JJ** [comment]
¿Dónde andáis?

**Comment by pbaeyens** [comment]
@M42, @fdavidcl y la gente de tercero están en un examen, creo. Yo no sé si me podré pasar hoy :( Y el resto no lo tengo muy claro.

**Comment by JJ** [comment]
¿Vendréis mañana por la mañana?
Lo digo por las pizzas...

**Comment by pbaeyens** [comment]
Creo que habíamos quedado en la Facultad de Ciencias en un aula que nos ceden para los seminarios, pero mejor que hables con @M42 (cuando esté presente, claro).

**Comment by JJ** [comment]
Si podéis, es mejor que vengáis por aquí.. no voy a ir repartiendo pizzas
por dos o tres sitios y la gracia del hackathon es hacerlo todo el mundo
juntos...

**Comment by pbaeyens** [comment]
Se lo digo a Mario cuando pueda y te digo qué vamos a hacer, que no sé si hay alguna razón para que estemos en Ciencias (?)
