### ISSUE TITLE
Limpieza de directorios

### ISSUE THREAD

**Issue by fdavidcl** [dgiim/blog#20]
Revisar y eliminar todo lo que sobre en `_drafts`, `_layouts`, etc.

**Comment by pbaeyens** [comment]
¿Borrar o no borrar?
@M42: 
- [P-NP](https://github.com/dgiim/blog/blob/gh-pages/_drafts/2014-4-12-p-np.md)
- [Teoría de Categorías](https://github.com/dgiim/blog/blob/gh-pages/_drafts/2014-5-15-categoriasIntro.md)
- [Banach-Tarski](https://github.com/dgiim/blog/blob/gh-pages/_drafts/2014-7-22-banachtarski.md)
- [Dimensión fractal](https://github.com/dgiim/blog/blob/gh-pages/_drafts/2014-7-30-dimension-fractal.md)

**Comment by M42** [comment]
Borrados los borradores vacíos en bbda4fb44fed61342595d486dc74d1ba2d590ae7.
Para el resto he creado una issue para terminarlos #25, #26.
