### ISSUE TITLE
Propuestas de nombres

### ISSUE THREAD

**Issue by fdavidcl** [dgiim/blog#21]

**Comment by fdavidcl** [comment]
Propuestas que van saliendo in da #hackathonugr:

* \math
* <s>return infinity</s> (existe)
* empty core
* math++
* kernel [in] panic
* make maths
* maths maQED
...?

**Comment by JJ** [comment]
math gems
CMAN (comprehensive Math archive network)

**Comment by M42** [comment]
Me temo que ninguna tuvo el apoyo suficiente para quitar el actual DGIIM. Creo que podríamos dejar el nombre, al menos por ahora. Salvo alguna propuesta o alguna idea que se me haya pasado para elegir nombre,  podemos cerrar la issue. @fdavidcl

**Comment by fdavidcl** [comment]
:+1:
