### ISSUE TITLE
¿Por qué no escribís algo sobre el día de Pi?

### ISSUE THREAD

**Issue by JJ** [dgiim/blog#22]
Además, hay un [libro de Pi](https://github.com/JJ/PiBook) hecho entre @psicobyte y un servidor.

**Comment by M42** [comment]
Vamos a empezar un post sobre cálculo de aproximaciones numéricas a Pi.

**Comment by JJ** [comment]
Genial... Si vais por el lado más lúdico https://github.com/JJ/PiBook/blob/master/pi-shades.pl
