### ISSUE TITLE
Poner iconos a los enlaces y cosas con Font Awesome

### ISSUE THREAD

**Issue by m-andres** [dgiim/blog#33]

**Comment by robertohueso** [comment]
En esta web http://allthefreestock.com/ hay gran variedad de recursos para la web con licencia Creative Commons Zero

**Comment by JJ** [comment]
¿Qué iconos queréis poner?

**Comment by m-andres** [comment]
Hemos puesto un lápiz :smile: 
Y de momento no vamos a poner más a la espera de un posible rediseño de la página.

**Comment by JJ** [comment]
Guay.

2015-03-14 13:12 GMT+01:00 M. Andrés <notifications@github.com>:

> Hemos puesto un lápiz [image: :smile:]
> Y de momento no vamos a poner más a la espera de un posible rediseño de la
> página.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dgiim/blog/issues/33#issuecomment-80394766>.
>



-- 
JJ
