### ISSUE TITLE
Rediseño del blog

### ISSUE THREAD

**Issue by m-andres** [dgiim/blog#37]
Reestructuración de los menús y demás cosas.

**Comment by fdavidcl** [comment]
Si hacéis pull y os pasáis por [color_options/](https://github.com/dgiim/blog/tree/gh-pages/color_options), podéis votar aquí por el color que queráis o proponer otros. He usado algunos de los colores de [Flat UI colors](http://flatuicolors.com/).

**Comment by robertohueso** [comment]
Si tengo que decidir alguno, votaría por Wetasphalt o Concrete, pero propongo, ¿Por qué no elegir aleatoriamente una de varias paletas de colores para cada visita? (Siempre que ésto no afecte a la experiencia del usuario)

**Comment by pbaeyens** [comment]
Yo votaría por alguno de esos dos (Wetasphalt o Concrete) también, me parece que son los que más pegan con el logo.

**Comment by fdavidcl** [comment]
Yo iría por uno de esos dos o el Orange. No creo que podamos elegir uno aleatorio a cada visita porque hay algunos ajustes que se pueden mejorar para según qué colores (el color de texto de la fecha y el del icono activo).

**Comment by pbaeyens** [comment]
Una cosa a considerar: El color del icono destacado tiene poco contraste con algunos temas y casi no se ve (?)

**Comment by fdavidcl** [comment]
A eso me refiero, cuando elijamos un color hay que ajustar eso y la fecha de los posts. No os preocupéis, sea el que sea lo ajustamos para que quede bien.

**Comment by pbaeyens** [comment]
Perdón, no había leído bien.

**Comment by M42** [comment]
Excepto quizá el `turquoise.png` que me chilla un poco, los veo todos bastante realizables.
