### ISSUE TITLE
MathJax no carga en algunos navegadores

### ISSUE THREAD

**Issue by fdavidcl** [dgiim/blog#39]
En algunos Chrome y en IE Mobile.

**Comment by fdavidcl** [comment]
La carga en Chrome + HTTPS arreglada en cf81d75c302d14a67b2b5da95ee28cbbc199795c para #45. Pendiente aún en IE Mobile.

**Comment by JJ** [comment]
Really? IE Mobile? No seŕia mejor ponerles un mensaje del tipo. "¿En serio
que todavía usa alguien IE y peor todavía en el móvil?"

**Comment by fdavidcl** [comment]
Nah, si el único que lo usa soy yo. Porque no tengo más opción, vaya. Si Opera Mini funcionase o sacaran Firefox iba yo a seguir usando IE... Pero bueno, por rigurosidad se queda esto pendiente :)

**Comment by JJ** [comment]
Aparentemente, mirando a la FAQ de Mathjax es compatible con IE>6. No dice
nada de IE mobile... ¿No tiene ninguna opción fallback?

**Comment by fdavidcl** [comment]
Es lo extraño, MathJax usa al menos 3 representaciones para el Latex (HTML/CSS, SVG, MathML) así que no debería fallar. Aunque a la vista de mathjax/MathJax#1085, tiene pinta que es culpa de MS, que hizo cosas raras con IE en la última actualización.

**Comment by fdavidcl** [comment]
Cierro esto por ahora, porque parece que no se puede arreglar en nuestro lado.
