### ISSUE TITLE
Post: Teorema Incompletitud Godel

### ISSUE THREAD

**Issue by makixun** [dgiim/blog#41]
Introducir de forma amena y sencilla el Teorema de Incompletitud de Godel.

**Comment by makixun** [comment]
Acabo de terminar la primera fase del post sobre Godel. Seguiré mejorándolo en los próximos días antes de publicarlo.

**Comment by makixun** [comment]
Seguiré avanzando durante las vacaciones.

**Comment by M42** [comment]
Por si ayudara, me acabo de encontrar esto: http://blog.plover.com/math/Gdl-Smullyan.html

**Comment by makixun** [comment]
Tengo que seguir con esto.... a ver si le saco tiempo.

Gracias por el link ;)
