### ISSUE TITLE
Tweet automático cuando se cierre un issue

### ISSUE THREAD

**Issue by m-andres** [dgiim/blog#44]
Gracias a la idea de @jj

**Comment by m-andres** [comment]
Probando las recetas de IFTTT (cerrando este issue).

**Comment by JJ** [comment]
;-)

2015-03-14 17:19 GMT+01:00 M. Andrés <notifications@github.com>:

> Closed #44 <https://github.com/dgiim/blog/issues/44>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dgiim/blog/issues/44#event-253797053>.
>



-- 
JJ

**Comment by m-andres** [comment]
Probando de nuevo
