### ISSUE TITLE
Añadir licencia al código

### ISSUE THREAD

**Issue by fdavidcl** [dgiim/blog#51]
Estamos usando jekyll/Jekyll (MIT) y yahoo/pure (BSD).

**Comment by M42** [comment]
Como ambas nos dejan libertad para decidir cómo licenciar el código, propongo por ahora GPLv3. Nótese que los posts están aparte en CC-BY-SA 3. ¿Deberíamos usar Creative Commons Version 4?

**Comment by pbaeyens** [comment]
No consigo encontrar ahora la fuente, pero las licencias Creative Commons 4.0 tenían problemas con Wikipedia si no recuerdo mal y por eso yo dije de dejarlo en la 3.0.

**Comment by M42** [comment]
Cada post puede licenciarse por separado. Se podría dejar alguno que copie algo directamente de WIkipedia como Creative Commons 3.0 (no sería lo habitual, pero hay casos #22) y por defecto usar la 4.0.
