### ISSUE TITLE
Images in _images don't work as a relative path

### ISSUE THREAD

**Issue by NCordon** [dgiim/blog#54]
As an example, there's an image at the end of the article Learning from Arch that doesn't show

**Comment by fdavidcl** [comment]
Directories starting with `_` are recognized as special directories for Jekyll and do not generate a folder when the site is built. We can use `images/` instead.

**Comment by NCordon** [comment]
Still doesn't work ;______;

**Comment by M42** [comment]
Is this still not solved? Commit b934a68 seems to assume this is solved. (?)

**Comment by fdavidcl** [comment]
It is solved indeed, although using `images/` instead of `_images/`.
