### ISSUE TITLE
Post: Fast inverse square root

### ISSUE THREAD

**Issue by M42** [dgiim/blog#56]
Acabo de encontrarme este [método](http://en.wikipedia.org/wiki/Fast_inverse_square_root) para calcular la inversa de la raíz cuadrada usando logaritmos y la representación binaria de un `float`. No tiene artículo en Wikipedia en castellano, así que escribir un artículo sobre esto podría ser interesante. Puede asignarse quien quiera escribirlo.

**Comment by NCordon** [comment]
Me lo quedo
