### ISSUE TITLE
Post: Disjoint-set forests

### ISSUE THREAD

**Issue by M42** [dgiim/blog#58]
Estudiar las posibles estructuras de datos para representar conjuntos disjuntos, como los [bosques de conjuntos disjuntos](http://en.wikipedia.org/wiki/Disjoint-set_data_structure). Son estructuras que soportan las funciones:
* `find`: Busca el subconjunto al que pertenece un elemento.
* `union`: Une dos subconjuntos en uno solo.
Quien quiera escribirlo puede asignarse.

**Comment by stringparser** [comment]
Me gusta :)
