### ISSUE TITLE
Post: Gerrymandering

### ISSUE THREAD

**Issue by tzae** [dgiim/blog#63]
Hacer un post sobre el [*gerrymandering*](http://es.wikipedia.org/wiki/Gerrymandering) y su relación con las matemáticas ([relacionado](http://www.maa.org/sites/default/files/pdf/upload_library/22/Polya/Hodge2011.pdf)).

**Comment by M42** [comment]
El artículo enlazado cuenta cómo definir un coeficiente para medir la convexidad y lo "natural" que es la línea fronteriza de una circunscripción electoral. Me parece interesante pero quizá insuficiente para un artículo.
Me gustaría hablar de más aspectos del gerrymandering, así que voy a buscar. ¿Tenías pensado tratar más temas?

**Comment by pbaeyens** [comment]
No tenía pensado nada más la verdad :( El autor de SMBC [preguntó](http://math.stackexchange.com/questions/38772) en StackExchange para hacer [este cómic](http://www.smbc-comics.com/?id=3047) y en la pregunta hay algún enlace más así que a lo mejor algo se puede sacar (?)
