### ISSUE TITLE
Utilizar tareas de rake para automatizar procesos

### ISSUE THREAD

**Issue by fdavidcl** [dgiim/blog#64]
Creación de posts y recursos, por ejemplo. ([Ejemplos](http://www.layouts-the.me/rake/2011/04/23/rake_tasks_for_jekyll/)).

**Comment by fdavidcl** [comment]
Ideas sobre esto para cuando me ponga a implementarlo:
* `rake post` debería además crear una nueva rama para trabajar con el post (probablemente en *_drafts*?) y sincronizarla con el repo remoto.
* `rake revision` podría dar a elegir una rama con un post a revisar y abrir una rama de revisión para editar lo que haga falta.

¿Más ideas de posibles tareas a automatizar?

**Comment by fdavidcl** [comment]
![rakecoming](https://cloud.githubusercontent.com/assets/909629/8890850/9ea66fbc-3310-11e5-9b0f-05c08bcfa031.png)

*It's coming...*

**Comment by M42** [comment]
Entiendo que esta está terminada con los últimos commits. Si se necesita añadir más funcionalidades se pueden añadir en otra issue.
