### ISSUE TITLE
Errores en el coloreado de sintaxis

### ISSUE THREAD

**Issue by M42** [dgiim/blog#65]
Escribiendo #55 me estoy dando cuenta de que la sintaxis se colorea incorrectamente o incluso no se colorea en algunos casos. Especialmente me preocupa este código:
```Haskell
prdcomm :: (a,b) -> (b,a)
prdcomm (x,y) = (y,x)

sumcomm :: Either a b -> Either b a
sumcomm (Left  x) = (Right x)
sumcomm (Right y) = (Left  y)
```
Que aquí en Github se colorea correctamente pero que no se colorea en el blog, por ejemplo en el commit 7f6e167946b4afa9247be201a57a70e908bdb41d puede observarse:

![ejemplo](https://cloud.githubusercontent.com/assets/5337877/6688727/0119081a-ccb6-11e4-9c91-00e186814179.png)

Me temo que el error sea externo, ¿alguna idea de dónde debe estar?

**Comment by JJ** [comment]
Normalmente el coloreado se hace con JavaScript en el cliente. Mira a ver
qué librería usa, si toma correctamente, si hay algún error...

**Comment by M42** [comment]
Acaba de solucionarlo @fdavidcl en fb61ec8b02381ee6f93a8791cd5f4a40da0b5535. HighlightJS detectaba automáticamente CoffeeScript en vez de Haskell. Y hay que sobreescribir el lenguaje que detecta automáticamente usando clases HTML en vez de Markdown.
