### ISSUE TITLE
Añadir las funcionalidades de #64 al README

### ISSUE THREAD

**Issue by M42** [dgiim/blog#66]
Escribir unas instrucciones en el `README` para hacer que los potenciales escritores usen `rake post` en la generación de sus posts. Quizá habría que añadirlo también a la guía de estilo.

**Comment by pbaeyens** [comment]
Para que funcionara se necesita instalar:
- `ruby` `rake` y `bundler`
- Las gemas `execjs`, `therubyracer` y `ffi`

**Comment by M42** [comment]
En general habría que reescribir el readme.md (#7) para facilitar la colaboración con el blog.
