### ISSUE TITLE
Post: Futurama theorem

### ISSUE THREAD

**Issue by M42** [dgiim/blog#74]
No me he parado a leerlo pero entiendo que es un teoremilla trivial sobre grupos de permutaciones. Si a alguien le apetece escribirlo con un poco de literatura; parece un resultado curioso. [Futurama theorem](http://theinfosphere.org/Futurama_theorem)

Quien lo escriba, que tenga cuidado con las licencias.

**Comment by m-andres** [comment]
Como dije, si nadie lo quiere me apunto a hacerlo :)
