### ISSUE TITLE
Foráneos

### ISSUE THREAD

**Issue by stringparser** [dgiim/blog#77]
Muy buenas, ¿se aceptan foráneos al doble grado? :)

**Comment by fdavidcl** [comment]
Hola!

Por supuesto, es la idea que tenemos ahora. Precisamente mañana (en el seminario en Ciencias) íbamos a hablar de cómo simplificar el proceso de confección, revisión y aceptación de artículos, sobre todo con #64 y poniendo visiblemente lo que acordemos para esto. Pásate si quieres para comentar cualquier cosa, o si no aquí mismo ^_^

**Comment by stringparser** [comment]
Yikes, acabo de verlo. Salgo ahora para ciencias :).

**Comment by stringparser** [comment]
Ok, he visto #64 y tengo ya el blog funcionando en el ordenata. Cierro este ;)
