### ISSUE TITLE
Post: Page Rank

### ISSUE THREAD

**Issue by andreshp** [dgiim/blog#78]
Explicar el algoritmo Page Rank utilizado por el motor de búsqueda de google desde un punto de vista matemático.

**Comment by makixun** [comment]
Tengo un libro muy bueno sobre google que creo que incluye PageRanko creo, si quieres un dia de estos te lo dejo.

**Comment by andreshp** [comment]
Perfecto, muchas gracias! Espero poder ponerme a escribirlo en Junio ^^

**Comment by M42** [comment]
Podría ser un momento para revivir este post, el otro día lo comentó @josemam. ¿Alguien se animaría a empezarlo por lo menos?
