### ISSUE TITLE
Usar KaTeX en lugar de MathJax

### ISSUE THREAD

**Issue by fdavidcl** [dgiim/blog#82]
[KaTeX](/khan/katex) ([khan.github.io/KaTeX/](https://khan.github.io/KaTeX/)) al parecer es más rápido que MathJax y tiene pinta de que funciona mejor. Habría que probar qué tal funciona y ver si lo podemos usar en el blog.

**Comment by JJ** [comment]
No digo que sea malo, pero la página me ha dejado colgado el Firefox.

**Comment by fdavidcl** [comment]
o.O yo estoy usando Firefox y no me ha pasado nada. De todas formas, estoy viendo que parece que está aún un poco verde y es más limitado que MathJax ([comparación](http://www.intmath.com/cg5/katex-mathjax-comparison.php)). Habrá que ver si es suficiente o hay que esperar.

**Comment by M42** [comment]
A mí también me lo ha dejado colgado. Firefox 38.0. Casi que nos vamos a esperar.

**Comment by stringparser** [comment]
Otra opción sería hacer el renderizar las fórmulas para incluirlas sin usar javascript en el navegador (véase [Khan/katex](https://github.com/Khan/KaTeX#server-side-rendering-or-rendering-to-a-string)). Con eso e incluir el CSS parece que es suficiente.

Aunque habría que meterse a ver cómo hace jekyll e incluirlo en las transformaciones que hay desde kramdown a html.

**Comment by fdavidcl** [comment]
@stringparser Eso sería fantástico, pero hasta donde yo sé en Github Pages no podemos incluir nada "programado" en el lado del servidor, no podemos incluir plugins para Jekyll siquiera :(. Miraré de todas formas por si hubiera alguna manera, gracias por el link.

**Comment by stringparser** [comment]
@fdavidcl cachis (si, acabo de verlo [aquí](http://jekyllrb.com/docs/plugins/)) yo creía que jekyll era una build tool pero estoy viendo que tiene una especie de servidor. 

Otra opción es no usar katex, es decir usar latex directamente (ver https://github.com/fgalindo/jekyll-liquid-latex-plugin) aunque no se cómo de bien saldrían las "ecuaciones" (supongo que serían imágenes sip, ver http://www.flx.cat/jekyll/2013/11/10/liquid-latex-jekyll-plugin.html). En cualquier caso esto último tampoco se puede por lo que dices antes :smile:.

**Comment by stringparser** [comment]
@fdavidcl ok, aquí está la solución https://github.com/jekyll/jekyll/issues/325, generar la web con jekyll y usar eso como las `gh-pages` (lo que dejaría esta rama como `master`). 

Por lo que veo [aquí](http://jekyllrb.com/docs/usage/) la carpeta `_site` es la implicada. Es decir, después de hacer `jekyll build` por defecto se genera la web en `_site`de format estática.

**Comment by fdavidcl** [comment]
@stringparser sip, eso lo habíamos debatido entre nosotros antes, y si hiciera mucha falta lo haríamos, pero la verdad es que parece más incómodo que si lo hace Github solo :stuck_out_tongue_closed_eyes:. De todas formas como aún tenemos que ampliar el Rakefile ( #64 ) para que casi todo se haga de forma programática y haya poca cosa que hacer manualmente, se podría intentar conseguir eso también. Gracias por las ideas :+1:.

**Comment by stringparser** [comment]
@fdavidcl haha, la verdad es que si complica la cosa a la hora de mantener una rama `master` y otra `gh-pages`. Yo he intentado tener una rama del mismo repositorio como una subcarpeta pero a git no le gusta. Mire una vez y estuve cerca de poder hacerlo con submodules pero nein!

**Comment by M42** [comment]
Entiendo que hasta que no tengamos servidor propio no podremos hacer nada aquí.

**Comment by M42** [comment]
Y ahora que lo tenemos, tampoco sé si debemos complicarnos en esto. MathJax se ha portado bien en todo lo que le hemos pedido a día de hoy.
