### ISSUE TITLE
Post: Topological Sort

### ISSUE THREAD

**Issue by andreshp** [dgiim/blog#83]
Explicar en qué consiste el orden topológico de un grafo dirigido, deducir cuándo existe y proporcionar un algoritmo O(|V| + |E|) para calcularlo.

**Comment by stringparser** [comment]
No se porqué siempre me gustan las cosas con grafos. Dejo aquí el artículo que he encontrado en wikipedia. https://en.wikipedia.org/wiki/Topological_sorting. Avisa si te pones a trabajar en el. Si tengo un día en el que tenga tiempo libre me gustaría hacerlo :)

**Comment by andreshp** [comment]
Todo tuyo ^^.

**Comment by stringparser** [comment]
Perfect. A ver si con este cumplo :D

**Comment by andreshp** [comment]
Te dejo mi implementación en Python. Hay un README en inglés explicándolo también.

https://github.com/andreshp/Algorithms/tree/master/Graphs/TopologicalSort

**Comment by stringparser** [comment]
Gracias! :)

**Comment by andreshp** [comment]
De nada! :)

**Comment by andreshp** [comment]
Lo último que tengo, dos problemas resolubles con la idea del orden topológico:

https://www.hackerrank.com/contests/projecteuler/challenges/euler079
https://www.hackerrank.com/contests/indeed-prime-challenge/challenges/course-dilemma

**Comment by stringparser** [comment]
Y la web además tiene una pinta muy buena :). 

He recordado que también una vez se tiene el grafo se puede relacionar con el cálculo de dimensiones fractales (usando el algoritmo de [box-counting](https://en.wikipedia.org/wiki/Box_counting)). Pero quizá eso merezca otro post a parte. La idea de este algoritmo es ir aumentando el tamaño de la caja y contar el número de clústeres en cada division. Con esto se puede tener una idea de la dimension real si el grafo representa algún tipo de estructura en 2 o 3 dimensiones. Esto lo tuve que hacer el último año de carrera y tengo código por ahí. Lo buscaré y abro un issue para hacer un post sobre eso.

**Comment by andreshp** [comment]
:+1:  Tiene muy buena pinta ^^
