### ISSUE TITLE
Errata en 'Convergencia puntual y convergencia uniforme'

### ISSUE THREAD

**Issue by NCordon** [dgiim/blog#86]
![blog](https://cloud.githubusercontent.com/assets/5649971/8677712/f0c60a6e-2a50-11e5-81da-847e1450f765.jpg)

Lo que se ve como un 1 debería ser un 5. Lo más extraño es que en el post en código fuente está correcto.

**Comment by fdavidcl** [comment]
El código fuente no importa porque Markdown hace la cuenta. Vaya, que si escribo

~~~
1. a
1. b
1. c
~~~

genera

1. a
1. b
1. c

Voy a mirar qué pasa a ver si sé arreglarlo.
