### ISSUE TITLE
Dibujar diagramas conmutativos

### ISSUE THREAD

**Issue by M42** [dgiim/blog#87]
He empezado un post sobre teoría de categorías y no estoy seguro de cómo dibujar los diagramas conmutativos. Mi primera idea era crearlos en LaTeX con [tikz-cd](https://www.ctan.org/pkg/tikz-cd) e insertarlos aquí como imagen. ¿Hay algún procedimiento más fácil?¿MathJax puede hacer algo con tikz-cd?

*Quizá relacionado con #72, aunque no creo que haya una solución común.*

**Comment by fdavidcl** [comment]
MathJax permite ([fuente](http://meta.math.stackexchange.com/questions/2324/how-to-draw-a-commutative-diagram)) dibujar diagramas conmutativos de [*AMScd*](http://www.jmilne.org/not/Mamscd.pdf). Lo que pasa es que estos diagramas no pueden tener flechas diagonales :confused:.

~~~latex
\require{AMScd} % No sé si el require es necesario ya
\begin{CD}
A     @>a>>  B\\
@VVbV        @VVcV\\
C     @>d>>  D
\end{CD}
~~~
[Prueba en HostMath](http://www.HostMath.com/Show.aspx?Code=%5Crequire%7BAMScd%7D%0A%5Cbegin%7BCD%7D%0AA%20%20%20%20%20%40%3Ea%3E%3E%20%20B%5C%5C%0A%40VVbV%20%20%20%20%20%20%20%20%40VVcV%5C%5C%0AC%20%20%20%20%20%40%3Ed%3E%3E%20%20D%0A%5Cend%7BCD%7D)

Otra solución es que los hagas en un programa de dibujo vectorial y pegues el código SVG tal cual en el post, los navegadores modernos entienden eso sin mucho problema.

Si encuentro algo más te digo.

**Comment by M42** [comment]
Parece que hay formas de escribir el diagrama con **tikz**, que es la librería buena para LaTeX, y pasarlas luego a **svg**: [tikz2svg](https://gist.github.com/jbenet/9449155).

**Comment by stringparser** [comment]
Que guay. Estoy pensando... si se puede hacer eso seguramente habrá una librería por ahí de latex2svg. Eso molaría bastante.

**Comment by fdavidcl** [comment]
Pues parece que sí, con una búsqueda rápida he encontrado [SVGLaTeX](http://svgkit.sourceforge.net/SVGLaTeX.html). Lo mismo hay más cosas similares

**Comment by stringparser** [comment]
¡Que bien! Gracias tio :)

**Comment by stringparser** [comment]
Esto le va a gustar a @M42 :D

https://gist.github.com/lierdakil/6a95278d02256a74a0fc

**Comment by M42** [comment]
Añadiéndole un \usepackage{tikz-cd} es solución en Haskell a la issue. Ya ves si le va a gustar. :)

Voy a escribir los diagramas en tikz-cd y llevármelos a **svg**. En cuanto lo pruebe cierro la issue.

**Comment by fdavidcl** [comment]
:clap: :clap: @stringparser Mola mucho el gist ese :D

**Comment by M42** [comment]
He añadido las imágenes. Usan al final **tikzcd** y **pdf2svg**. He añadido los originales en LaTeX para que todo el proceso sea reproducible.

**Comment by M42** [comment]
Me falta entender cómo enlazar las imágenes. No puedo usar `https://raw.githubusercontent.com` por lo que cuentan [aquí](http://stackoverflow.com/a/21521184/2552681). La opción que me queda es enlazarla directamente como ![](http://dgiim.github.io/blog/images/n-categories/f-id.svg). ¿Dará algún problema?

Por otro lado, haciéndolo así no puedo previsualizarla cuando hago **jekyll serve** pero este es un problema menor.

No he probado a introducir el código del .svg directamente en Markdown. Seguramente sea lo más cómodo, pero no me convence copiar y pegar el código, sobre todo para que esté en un archivo separado y sea luego reproducible.

**Comment by fdavidcl** [comment]
Prueba con esto:

~~~
![]({{ site.baseurl }}/images/blabla.svg)
~~~

*[He arreglado la [guía de estilo](https://dgiim.github.io/blog/styleguide/) para recomendar este formato]*

Aun así, aunque funcionase en local habría que probar de alguna forma que los servidores de GitHub también van a servir las imágenes, que me da a mí que no :/

Meter el código SVG dentro del post casi seguro que valdría. No sé si podríamos intentar usar los mecanismos de `include` de Jekyll para mantener el SVG en un archivo aparte.

**Comment by M42** [comment]
Con esto funciona perfectamente. Falta centrarla y aumentarla de tamaño. Eso se puede hacer a lo mejor con `{: .fig.med}` o algo parecido como hicimos con el post de Arch. Cuando termine el post buscamos un estilo con el que quede bien.

**Comment by M42** [comment]
Voy a dejar el post de lado por ahora. Con la versión actual, si alguien quiere, puede encargarse de esta issue para conseguir que las images se vean bien en la introducción. Me "desasigno".

**Comment by M42** [comment]
Se pueden acabar metiendo como .svg
