### ISSUE TITLE
Separar los recursos del resto del blog

### ISSUE THREAD

**Issue by M42** [dgiim/blog#88]
Dejarlos en un repositorio independiente del blog para evitar mezclarlos. Relacionado con #52, aunque este caso me parece incluso más claro. Entiendo que podríamos separarlos sin usar siquiera submódulos.

**Comment by fdavidcl** [comment]
Tengo una versión en [dgiim.github.io/awesome/](https://dgiim.github.io/awesome/) a falta de posibles arreglos y retoques. Mirad a ver qué tal. Podéis modificar lo que queráis. Discutan pls.

**Comment by M42** [comment]
En lo que respecta a separación, lo veo perfecto. A lo mejor podemos discutir cosas del estilo, pero eso ya va para otra issue en el otro repositorio.

Aquí queda por borrar `/resources` y cerrar esta issue.
