### ISSUE TITLE
Usar integración continua

### ISSUE THREAD

**Issue by M42** [dgiim/blog#9]
Para comprobar que la generación de la página funciona y para comprobar la ortografía, por ejemplo.

**Comment by JJ** [comment]
Si necesitáis ayuda, avisad. Podéis mirar alguno de mis libros (o novelas),
esto
http://curso-nube.github.io/test/tdd/broccoli/gulp/grunt/continuous%20integration/ic/ci/makefile/build%20tools/deployment/despliegue/2014/12/09/desarrollo-basado-en-pruebas/
o las guías de Travis-CI (para mi el más sencillo, aunque es un poco lento)

**Comment by M42** [comment]
Por ahora no vamos a añadir más a la integración continua. Si hace falta luego seguiremos con esta u otra issue.
