### ISSUE TITLE
Alojamiento y nombre de dominio

### ISSUE THREAD

**Issue by fdavidcl** [dgiim/blog#96]
Esto para ir apuntando ideas/posibilidades para el tema del hosting y del nombre de dominio.

**Comment by fdavidcl** [comment]
Soluciones temporales (gratuitas) son hosting en Azure y dominio con Namecheap en el TLD .me. Estamos abiertos a otras ideas y apaños que se puedan hacer, sobre todo para largo plazo.

**Comment by andreshp** [comment]
El grupo de investigación [Soft Computing and Intelligent Information Systems](http://sci2s.ugr.es/) nos ha ofrecido usar su servidor y una dirección http://sci2s.ugr.es/dgmii/...

**Comment by andreshp** [comment]
Como hemos presentado el blog al certamen de proyectos libres de la UGR, no sé si es viable alojar el blog en servidores y dominios de la entidad organizadora.

**Comment by andreshp** [comment]
> @fdavidcl - Alojar el blog en la nube
> Una solución para esto (temporal pero con bastante plazo) podría ser DigitalOcean, que con el paquete Education de GitHub tenemos (cada uno) 100$ bonificados, que da para mucho tiempo (el plan más básico cuesta 5$/mes). Habría que comprobar que los códigos se pueden acumular, para meterlos todos en la misma cuenta.

> La única pega es que antes de meter ningún código hay que añadir otra forma de pago (tarjeta o paypal) así que habría que estudiarlo.

**Comment by M42** [comment]
La pega del DigitalOcean no me parece muy grande. Si se puede usar esto y se puede conseguir un nombre de dominio, está todo hecho.

**Comment by fdavidcl** [comment]
Para el dominio, si no tenemos nada mejor podemos usar uno de [Freenom](http://www.freenom.com/es), que son en TLDs un poco raros, pero gratis y renovables gratis cada año. No es lo ideal pero puede apañarlo...

**Comment by NCordon** [comment]
https://nc.me/

Entiendo que la página esa proporciona dominios .me gratuitos para estudiantes (?)

**Comment by fdavidcl** [comment]
@NCordon Sip (son Namecheap), a través de Github duran un año, tras eso cuestan ~16€. Desde la propia página sólo permite a universidades estadounidenses, inglesas y canadienses.

**Comment by NCordon** [comment]
@fdavidcl ¿y cuál es el problema de eso? ¿Que buscamos algo permanente?

**Comment by jesusjmma** [comment]
Y con lo bien que funciona todo esto... ¿No se podría probar a pedir una pequeña subvención anual para el nombre del dominio y el hosting a la ETSIIT? Si no tengo entendido muy mal, a la delegación les pagan anualmente un hosting muy bueno y ni siquiera lo están utilizando.

**Comment by jesusjmma** [comment]
¿Cuanto puede costar un hosting?

**Comment by fdavidcl** [comment]
Pues no demasiado, mientras no tengamos mucho tráfico. De hecho hace unos días probé a desplegar el [blog en Openshift](https://jekyll-fdavidcl.rhcloud.com/) de gratis y no funciona mal (lo único malo es que el tiempo de actividad -en el que la aplicación está "encendida"- es limitado, con una cuenta de pago no pasaría...). Además, ahora mismo contamos con un poco de espacio prestado por la OSL en [tux.ugr.es](http://tux.ugr.es/) pero aún no nos hemos puesto a usarlo.

**Comment by M42** [comment]
Si no hay nada en contra, creo que deberíamos empezar a usar ese espacio.

**Comment by jesusjmma** [comment]
Llamadme loco, pero he pensado en organizar un barril y sacar dinero para
esto. No sé si os gusta la idea, pero los de 1º y 2º van a participar.

**Comment by M42** [comment]
Se cierra al cerrar #105.
