### ISSUE TITLE
Rakefile necesita instalar git

### ISSUE THREAD

**Issue by M42** [dgiim/blog#98]
Cuando se intenta ejecutar `rake post` se obtiene el siguiente error:
```
rake aborted!
LoadError: cannot load such file -- git
/home/andreshp/SeminariosDobleGrado/blog/Rakefile:24:in `block in <top (required)>'
Tasks: TOP => post
(See full trace by running task with --trace)
```
Porque no está instalado git como librería de ruby. Necesita ejecutar antes:
``` bash
sudo gem install git
```
Para que funcione correctamente.

Esto habría que indicarlo en el propio Rakefile, o dar un mensaje de error más explícito.

**Comment by fdavidcl** [comment]
Es que cambié el Gemfile, tenéis que volver a hacer `bundle install`

**Comment by M42** [comment]
Y eso sí está indicado en la guía de Jekyll del readme.md. Cierro, aunque a @andreshp le están dando errores todavía, que se pueden tratar por otra issue.
